name: Continuous Integration

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          version: 0.0.2-preview.1
          token: ${{github.token}}
